version: '2.4'

services:
  postgres:
    image: 'postgres:15.6'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '54321:5432' # Postgres runs locally at 54321
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_DB: keycloak
      POSTGRES_PASSWORD: password

  # Values from https://www.keycloak.org/getting-started/getting-started-docker
  keycloak:
    image: 'quay.io/keycloak/keycloak:24.0.2'
    ports:
      - '8888:8080' # Keycloak runs locally at 8888
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
    command: 'start-dev'
    depends_on:
      - postgres


volumes:
  postgres:
